import React, { useState } from "react";
import axios from "axios";

function AdminDashboard() {
  const [title, setTitle] = useState("");
    const [author, setAuthor] = useState("");
      const [description, setDescription] = useState("");
        const [price, setPrice] = useState("");

          const handleSubmit = async (e) => {
              e.preventDefault();

                  try {
                        await axios.post(`${process.env.REACT_APP_API_URL}/stories`, {
                                title,
                                        author,
                                                description,
                                                        price: price ? parseFloat(price) : 0,
                                                              });

                                                                    alert("✅ Story uploaded successfully!");
                                                                          setTitle("");
                                                                                setAuthor("");
                                                                                      setDescription("");
                                                                                            setPrice("");
                                                                                                } catch (error) {
                                                                                                      console.error("Error uploading story:", error);
                                                                                                            alert("❌ Failed to upload story. Check your backend.");
                                                                                                                }
                                                                                                                  };

                                                                                                                    return (
                                                                                                                        <div style={styles.container}>
                                                                                                                              <h2>📚 Storix Admin Dashboard</h2>
                                                                                                                                    <form onSubmit={handleSubmit} style={styles.form}>
                                                                                                                                            <input
                                                                                                                                                      type="text"
                                                                                                                                                                placeholder="Story Title"
                                                                                                                                                                          value={title}
                                                                                                                                                                                    onChange={(e) => setTitle(e.target.value)}
                                                                                                                                                                                              style={styles.input}
                                                                                                                                                                                                        required
                                                                                                                                                                                                                />
                                                                                                                                                                                                                        <input
                                                                                                                                                                                                                                  type="text"
                                                                                                                                                                                                                                            placeholder="Author Name"
                                                                                                                                                                                                                                                      value={author}
                                                                                                                                                                                                                                                                onChange={(e) => setAuthor(e.target.value)}
                                                                                                                                                                                                                                                                          style={styles.input}
                                                                                                                                                                                                                                                                                    required
                                                                                                                                                                                                                                                                                            />
                                                                                                                                                                                                                                                                                                    <textarea
                                                                                                                                                                                                                                                                                                              placeholder="Story Description"
                                                                                                                                                                                                                                                                                                                        value={description}
                                                                                                                                                                                                                                                                                                                                  onChange={(e) => setDescription(e.target.value)}
                                                                                                                                                                                                                                                                                                                                            style={styles.textarea}
                                                                                                                                                                                                                                                                                                                                                      required
                                                                                                                                                                                                                                                                                                                                                              />
                                                                                                                                                                                                                                                                                                                                                                      <input
                                                                                                                                                                                                                                                                                                                                                                                type="number"
                                                                                                                                                                                                                                                                                                                                                                                          placeholder="Price (₦0 for free)"
                                                                                                                                                                                                                                                                                                                                                                                                    value={price}
                                                                                                                                                                                                                                                                                                                                                                                                              onChange={(e) => setPrice(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                        style={styles.input}
                                                                                                                                                                                                                                                                                                                                                                                                                                />
                                                                                                                                                                                                                                                                                                                                                                                                                                        <button type="submit" style={styles.button}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                  Upload Story
                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const styles = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        container: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            textAlign: "center",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                padding: "40px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    fontFamily: "Arial, sans-serif",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        form: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            display: "flex",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                flexDirection: "column",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    alignItems: "center",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        gap: "10px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            input: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                padding: "10px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    width: "300px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        borderRadius: "5px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            border: "1px solid #ccc",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                textarea: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    width: "300px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        height: "100px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            padding: "10px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                borderRadius: "5px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    border: "1px solid #ccc",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        button: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            padding: "10px 20px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                backgroundColor: "#ff0000",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    color: "white",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        border: "none",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            borderRadius: "5px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                cursor: "pointer",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  export default AdminDashboard;