// src/components/Login.js
import React, { useState } from "react";
import axios from "axios";
import "./Login.css";

const API_URL = process.env.REACT_APP_API_URL;

export default function Login({ onLogin }) {
  const [email, setEmail] = useState("");
    const [password, setPassword] = useState("");
      const [showPassword, setShowPassword] = useState(false);
        const [loading, setLoading] = useState(false);

          const handleSubmit = async (e) => {
              e.preventDefault();
                  setLoading(true);
                      try {
                            const res = await axios.post(`${API_URL}/api/auth/login`, { email, password });
                                  const user = res.data.user;
                                        localStorage.setItem("user", JSON.stringify(user));
                                              onLogin();

                                                    alert("✅ Login successful!");

                                                          // Redirect based on role
                                                                if (user.role === "owner") {
                                                                        window.location.href = "/owner/dashboard";
                                                                              } else {
                                                                                      window.location.href = "/stories";
                                                                                            }

                                                                                                } catch (err) {
                                                                                                      console.error("Login failed:", err);
                                                                                                            alert("❌ Login failed. Please check your email or password.");
                                                                                                                } finally {
                                                                                                                      setLoading(false);
                                                                                                                          }
                                                                                                                            };

                                                                                                                              return (
                                                                                                                                  <div className="login-container">
                                                                                                                                        <div className="login-box">
                                                                                                                                                <h1 className="app-title">Storix</h1>
                                                                                                                                                        <p className="tagline">Where stories come alive</p>

                                                                                                                                                                <form onSubmit={handleSubmit}>
                                                                                                                                                                          <input
                                                                                                                                                                                      type="email"
                                                                                                                                                                                                  placeholder="Email address"
                                                                                                                                                                                                              value={email}
                                                                                                                                                                                                                          onChange={(e) => setEmail(e.target.value)}
                                                                                                                                                                                                                                      required
                                                                                                                                                                                                                                                />

                                                                                                                                                                                                                                                          <div className="password-container">
                                                                                                                                                                                                                                                                      <input
                                                                                                                                                                                                                                                                                    type={showPassword ? "text" : "password"}
                                                                                                                                                                                                                                                                                                  placeholder="Password"
                                                                                                                                                                                                                                                                                                                value={password}
                                                                                                                                                                                                                                                                                                                              onChange={(e) => setPassword(e.target.value)}
                                                                                                                                                                                                                                                                                                                                            required
                                                                                                                                                                                                                                                                                                                                                        />
                                                                                                                                                                                                                                                                                                                                                                    <button
                                                                                                                                                                                                                                                                                                                                                                                  type="button"
                                                                                                                                                                                                                                                                                                                                                                                                className="show-btn"
                                                                                                                                                                                                                                                                                                                                                                                                              onClick={() => setShowPassword(!showPassword)}
                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                        {showPassword ? "Hide" : "Show"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button type="submit" className="login-btn" disabled={loading}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {loading ? "Logging in..." : "Log In"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </form>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="divider"></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <a href="/register" className="create-account">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Create New Account
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }