import React, { useState, useEffect } from "react";
import axios from "axios";
import "./OwnerDashboard.css";

const API_URL = process.env.REACT_APP_API_URL;

export default function OwnerDashboard() {
  const [password, setPassword] = useState("");
    const [loggedIn, setLoggedIn] = useState(false);
      const [visits, setVisits] = useState(0);
        const [title, setTitle] = useState("");
          const [description, setDescription] = useState("");
            const [price, setPrice] = useState("");

              // Handle owner password login
                const handleLogin = () => {
                    if (password === "Storix/Wiz.2025") {
                          setLoggedIn(true);
                                fetchVisits();
                                    } else {
                                          alert("❌ Invalid owner password!");
                                              }
                                                };

                                                  // Fetch number of site visits from backend
                                                    const fetchVisits = async () => {
                                                        try {
                                                              const res = await axios.get(`${API_URL}/api/visits`);
                                                                    setVisits(res.data.count || 0);
                                                                        } catch (err) {
                                                                              console.error("Error fetching visits:", err);
                                                                                    alert("Failed to fetch visits.");
                                                                                        }
                                                                                          };

                                                                                            // Handle posting a new story
                                                                                              const handlePost = async (e) => {
                                                                                                  e.preventDefault();
                                                                                                      try {
                                                                                                            await axios.post(`${API_URL}/api/stories`, {
                                                                                                                    title,
                                                                                                                            description,
                                                                                                                                    price,
                                                                                                                                          });
                                                                                                                                                alert("✅ Story posted successfully!");
                                                                                                                                                      setTitle("");
                                                                                                                                                            setDescription("");
                                                                                                                                                                  setPrice("");
                                                                                                                                                                      } catch (err) {
                                                                                                                                                                            console.error("Error posting story:", err);
                                                                                                                                                                                  alert("❌ Failed to post story.");
                                                                                                                                                                                      }
                                                                                                                                                                                        };

                                                                                                                                                                                          // === Owner Login Page ===
                                                                                                                                                                                            if (!loggedIn)
                                                                                                                                                                                                return (
                                                                                                                                                                                                      <div className="owner-login">
                                                                                                                                                                                                              <h2>Owner Login</h2>
                                                                                                                                                                                                                      <input
                                                                                                                                                                                                                                type="password"
                                                                                                                                                                                                                                          placeholder="Enter owner password"
                                                                                                                                                                                                                                                    value={password}
                                                                                                                                                                                                                                                              onChange={(e) => setPassword(e.target.value)}
                                                                                                                                                                                                                                                                      />
                                                                                                                                                                                                                                                                              <br />
                                                                                                                                                                                                                                                                                      <button onClick={handleLogin}>Login</button>
                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                );

                                                                                                                                                                                                                                                                                                  // === Dashboard ===
                                                                                                                                                                                                                                                                                                    return (
                                                                                                                                                                                                                                                                                                        <div className="dashboard-container">
                                                                                                                                                                                                                                                                                                              <h2 className="dashboard-header">📊 Owner Dashboard</h2>
                                                                                                                                                                                                                                                                                                                    <p className="stats">Total Visits: {visits}</p>

                                                                                                                                                                                                                                                                                                                          <h3>✍️ Post a New Story</h3>
                                                                                                                                                                                                                                                                                                                                <form onSubmit={handlePost}>
                                                                                                                                                                                                                                                                                                                                        <input
                                                                                                                                                                                                                                                                                                                                                  type="text"
                                                                                                                                                                                                                                                                                                                                                            placeholder="Title"
                                                                                                                                                                                                                                                                                                                                                                      value={title}
                                                                                                                                                                                                                                                                                                                                                                                onChange={(e) => setTitle(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                          required
                                                                                                                                                                                                                                                                                                                                                                                                  />
                                                                                                                                                                                                                                                                                                                                                                                                          <textarea
                                                                                                                                                                                                                                                                                                                                                                                                                    placeholder="Description"
                                                                                                                                                                                                                                                                                                                                                                                                                              value={description}
                                                                                                                                                                                                                                                                                                                                                                                                                                        onChange={(e) => setDescription(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                  required
                                                                                                                                                                                                                                                                                                                                                                                                                                                          ></textarea>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            type="number"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      placeholder="Price (Naira, optional)"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                value={price}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onChange={(e) => setPrice(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button type="submit">Post Story</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }