import React, { useState } from "react";
import axios from "axios";

const API_URL = process.env.REACT_APP_API_URL;

export default function Register() {
  const [name, setName] = useState("");
    const [email, setEmail] = useState("");
      const [password, setPassword] = useState("");
        const [loading, setLoading] = useState(false);

          const handleRegister = async (e) => {
              e.preventDefault();
                  setLoading(true);
                      try {
                            const res = await axios.post(
                                    `${API_URL}/api/auth/register`,
                                            { name, email, password },
                                                    { withCredentials: true }
                                                          );
                                                                alert("✅ Account created successfully!");
                                                                      console.log("Response:", res.data);
                                                                            window.location.href = "/login";
                                                                                } catch (err) {
                                                                                      console.error("Registration failed:", err.response?.data || err.message);
                                                                                            alert("❌ Registration failed.");
                                                                                                } finally {
                                                                                                      setLoading(false);
                                                                                                          }
                                                                                                            };

                                                                                                              return (
                                                                                                                  <div style={styles.container}>
                                                                                                                        <h2>Create Your Storix Account</h2>
                                                                                                                              <form onSubmit={handleRegister} style={styles.form}>
                                                                                                                                      <input
                                                                                                                                                type="text"
                                                                                                                                                          placeholder="Full Name"
                                                                                                                                                                    onChange={(e) => setName(e.target.value)}
                                                                                                                                                                              required
                                                                                                                                                                                        style={styles.input}
                                                                                                                                                                                                />
                                                                                                                                                                                                        <input
                                                                                                                                                                                                                  type="email"
                                                                                                                                                                                                                            placeholder="Email"
                                                                                                                                                                                                                                      onChange={(e) => setEmail(e.target.value)}
                                                                                                                                                                                                                                                required
                                                                                                                                                                                                                                                          style={styles.input}
                                                                                                                                                                                                                                                                  />
                                                                                                                                                                                                                                                                          <input
                                                                                                                                                                                                                                                                                    type="password"
                                                                                                                                                                                                                                                                                              placeholder="Password"
                                                                                                                                                                                                                                                                                                        onChange={(e) => setPassword(e.target.value)}
                                                                                                                                                                                                                                                                                                                  required
                                                                                                                                                                                                                                                                                                                            style={styles.input}
                                                                                                                                                                                                                                                                                                                                    />
                                                                                                                                                                                                                                                                                                                                            <button type="submit" style={styles.button} disabled={loading}>
                                                                                                                                                                                                                                                                                                                                                      {loading ? "Creating..." : "Register"}
                                                                                                                                                                                                                                                                                                                                                              </button>
                                                                                                                                                                                                                                                                                                                                                                    </form>
                                                                                                                                                                                                                                                                                                                                                                          <p>
                                                                                                                                                                                                                                                                                                                                                                                  Already have an account?{" "}
                                                                                                                                                                                                                                                                                                                                                                                          <a href="/login" style={styles.link}>Login</a>
                                                                                                                                                                                                                                                                                                                                                                                                </p>
                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                      const styles = {
                                                                                                                                                                                                                                                                                                                                                                                                        container: {
                                                                                                                                                                                                                                                                                                                                                                                                            textAlign: "center",
                                                                                                                                                                                                                                                                                                                                                                                                                padding: "40px",
                                                                                                                                                                                                                                                                                                                                                                                                                    background: "#fff",
                                                                                                                                                                                                                                                                                                                                                                                                                        borderRadius: "8px",
                                                                                                                                                                                                                                                                                                                                                                                                                            margin: "20px auto",
                                                                                                                                                                                                                                                                                                                                                                                                                                width: "90%",
                                                                                                                                                                                                                                                                                                                                                                                                                                    maxWidth: "400px",
                                                                                                                                                                                                                                                                                                                                                                                                                                        boxShadow: "0 4px 10px rgba(0,0,0,0.1)"
                                                                                                                                                                                                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                                                                                                                                                                                                            form: { display: "flex", flexDirection: "column", gap: "15px" },
                                                                                                                                                                                                                                                                                                                                                                                                                                              input: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                  padding: "12px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                      borderRadius: "5px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                          border: "1px solid #ddd",
                                                                                                                                                                                                                                                                                                                                                                                                                                                              fontSize: "16px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  button: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      backgroundColor: "#e60000",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          color: "white",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              padding: "12px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  border: "none",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      borderRadius: "5px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          cursor: "pointer",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              fontSize: "16px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  link: { color: "#e60000", textDecoration: "none", fontWeight: "bold" },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  };